name: 2023
on: [push]
  # schedule:
  #   - cron: '0 14 * * MON'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install setuptools
        run: python -m pip install --upgrade setuptools==56.0.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run
        run: python main.py --func all
      - name: Get current date
        id: date
        run: echo "current_date=$(date '+%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: git
        run: |
          git config --global user.email "zhout50@163.com"
          git config --global user.name "ZutJoe"
          git checkout -b dev
          git add .
          git commit -m "${{ steps.date.outputs.current_date }} update"
          git push
